# Use the httpd-parent image as base
FROM quay.io/redhattraining/httpd-parent

LABEL io.openshift.expose-services="8080:http" \
      io.k8s.display.name="Apache HTTP Server" \
      io.k8s.description="A basic Apache HTTP Server child image, using ONBUILD" \
      io.openshift.tags="apache, httpd"

EXPOSE 8080

RUN chgrp -R 0 /var/log/httpd /var/run/httpd && \
    chown -R g=u /var/log/httpd /var/run/httpd && \
    sed -i 's/Listen 80/Listen 8080/g' /etc/httpd/conf/httpd.conf && \
    sed -i 's/ServerName www.example.com:80/ServerName 0.0.0.0:8080' /etc/httpd/conf/httpd.conf

USER 1001
